# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run pyttests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up environment
      run: |
          cd backend/
          python3 -m venv venv
          venv\Scripts\activate
          $env:FLASK_APP = "server.py"
          $env:FLASK_ENV = "development"
          pip install -r requirements.txt
          flask run
    - name: Run tests
      run: |
        pytest
